### ISSUE TITLE
SONiC Processes running on Edgecore Switch

### ISSUE THREAD

**Issue by abhiranjeet** [Azure/SONiC#814]
Hi !

**What I did ?**

1. Built a ONIE-compatible .bin installer with `INCLUDE_KUBERNETES=y` and loaded it on an Edgecore Switch 
2. Joined the switch to a Kubernetes cluster where the master node is a Debian 10 Buster VM
3. Deployed a snmp daemonset manifest using kubectl from master.
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: snmp
spec:
  template:
    metadata:
      labels:
        name: snmp
    spec:
      hostname: sonic
      hostNetwork: true
      containers:
      - name: snmp
        image: abhinavstl/docker-snmp-brcm:source
        name: snmp
        tty: true
        env:
        - name: OWNER
          value: "kube"
        securityContext:
          privileged: true
        volumeMounts:
        - name: sonic
          mountPath: /etc/sonic
          readOnly: true
        - name: scripts
          mountPath: /usr/share/sonic/scripts
          readOnly: true
        - name: redis
          mountPath: /var/run/redis
          readOnly: false
        - name: redis-chassis
          mountPath: /var/run/redis-chassis
          readOnly: true
        - name: hwsku
          mountPath: /usr/share/sonic/hwsku/
          readOnly: true
        - name: platform
          mountPath: /usr/share/sonic/platform/
          readOnly: true
        imagePullPolicy: IfNotPresent
      volumes:
      - name: sonic
        hostPath:
          path: /etc/sonic
      - name: redis
        hostPath:
          path: /var/run/redis
      - name: redis-chassis
        hostPath:
          path: /var/run/redis-chassis
      - name: scripts
        hostPath:
          path: /usr/share/sonic/scripts
      - name: hwsku
        hostPath:
          path: /usr/share/sonic/device/x86_64-accton_as7712_32x-r0/Accton-AS7712-32X
      - name: platform
        hostPath:
          path: /usr/share/sonic/device/x86_64-accton_as7712_32x-r0
      nodeName: sonic
#      nodeSelector:
#        snmp_enabled: "true"
#        lldp_enabled: "true"
  selector:
    matchLabels:
      name: snmp
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
```

**Expected Result**

1. The snmp daemonset should get deployed on the switch 
2. The snmp processes inside the container should start

**Actual Result**

1. The daemonset gets deployed successfully (checked from kubectl get daemonsets)
2. The processes inside the container do not start

Any suggestions ?

Thanks !
